# Generated by Django 5.1.6 on 2025-02-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('property_name', models.CharField(max_length=255)),
                ('acre_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('road_width', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
